# Build the website
script:
  - mkdir public
  - cp -r  ./* public/

# Deploy to GitHub pages
deploy:
  provider: pages
  skip_cleanup: true
  target_branch: master
  github_token: $GITHUB_TOKEN
  local_dir: public
  verbose: true
  on:
    branch: build
